### ISSUE TITLE
Is this repo alive?

### ISSUE THREAD

**Issue by codeskyblue** [cuitteam/RealFPS#1]

**Comment by nicebug** [comment]
actually,inactivity.  so do you have any idea about this repo?

**Comment by codeskyblue** [comment]
我对java还底层的东西都不是很熟，只能从头学起，看能不能接下这个项目。

**Comment by nicebug** [comment]
可以啊， 欢迎！！！ 不知道你有什么想法，可否简单讲解下

**Comment by nicebug** [comment]
我可以拉上另外一个同学，一起讨论下

**Comment by codeskyblue** [comment]
最近遇到个问题，inject surfaceflinger 时候dlopen都失败。  inject别的进程反而没问题。

**Comment by nicebug** [comment]
有没有error log  能否贴下

**Comment by nicebug** [comment]
另外你注入的app是否有壳之类的保护？

**Comment by codeskyblue** [comment]
@nicebug 注入的程序是 surfaceflinger，不是什么app。 感觉你概念理解的有点问题。

**Comment by nicebug** [comment]
有log的话贴下log吧。。

**Comment by codeskyblue** [comment]
完全没log啊，所以说注入才失败

**Comment by nicebug** [comment]
我遇到的是注入成功但获取fps失败，你注入失败的问题可能可以从如下方面查找下：
1.libsurfaceflinger.so，find下查找下测试机上libsurfaceflinger.so的路径
2.如果获取got表失败，可以试试用hook_eglSwapBuffers这个注释掉的方法
以上请参考
